print("Digite o A:")
A= float(input())
print("Digite o B:")
B= float(input())
print("Digite o C:")
C= float(input())
print("Digite o D:")
D= float(input())
print("A SOMA de A com B é:",A+B)
print("A MULTIPLICACAO de A com B é:",A*B)
print("A SOMA de A com C é:",A+C)
print("A MULTIPLICACAO de A com C é:",A*C)
print("A SOMA de A com D é:",A+D)
print("A MULTIPLICACAO de A com D é:",A*D)
print("A SOMA de B com C é:",B+C)
print("A MULTIPLICACAO de B com C é:",B*C)
print("A SOMA de B com D é:",B+D)
print("A MULTIPLICACAO de B com D é:",B*D)
print("A SOMA de C com D é:",C+D)
print("A MULTIPLICACAO de C com D é:",C*D)